nodeLinker: node-modules

npmPublishAccess: public

packageExtensions:
  "@algolia/autocomplete-preset-algolia@*":
    peerDependenciesMeta:
      "@algolia/client-search":
        optional: true
  "@docusaurus/theme-common@*":
    peerDependenciesMeta:
      prism-react-renderer:
        optional: true
  "@docusaurus/utils@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
      react:
        optional: true
      react-dom:
        optional: true
      webpack:
        optional: true
  "@easyops-cn/docusaurus-search-local@*":
    peerDependenciesMeta:
      "@docusaurus/theme-common":
         optional: true
  "@nrwl/devkit@*":
    peerDependenciesMeta:
      nx:
        optional: true
  "@phenomnomnominal/tsquery@*":
    peerDependenciesMeta:
      typescript:
       optional: true
  eslint-utils@*:
    peerDependenciesMeta:
      eslint:
        optional: true
  fork-ts-checker-webpack-plugin@*:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true
  postcss-scss@*:
    peerDependenciesMeta:
      postcss:
        optional: true

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-3.5.0.cjs
