nodeLinker: node-modules

npmPublishAccess: public

packageExtensions:
  "@docusaurus/theme-common@*":
    peerDependenciesMeta:
      prism-react-renderer:
        optional: true
  "@docusaurus/utils@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
      react:
        optional: true
      react-dom:
        optional: true
      webpack:
        optional: true
  eslint-utils@*:
    peerDependenciesMeta:
      eslint:
        optional: true
  fork-ts-checker-webpack-plugin@*:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true
  postcss-scss@*:
    peerDependenciesMeta:
      postcss:
        optional: true

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-3.2.3.cjs
